### ISSUE TITLE
Show Disabled Inventory/Skills API Status

### ISSUE THREAD

**Issue by IHadN0Idea** [SubAt0m1c/HateCheaters#1]
When a player has disabled their inventory or skills API, show this status in the title instead of displaying an empty inventory/wardrobe or skills as zero. 
If the player's API status isn't available within the current API request, consider determining the status based on missing data (for example, empty inventory list)

**Comment by SubAt0m1c** [comment]
Probably a good idea, ill get to it at some point.

**Comment by SubAt0m1c** [comment]
Added for next release
